using System.Net;
using System.Net.Mail;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;

namespace MagicVilla_VillaAPI.Services
{
    public class EmailNotificationService : IEmailNotificationService
    {
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _config;
        private readonly ILogger<EmailNotificationService> _logger;

        public EmailNotificationService(
            ApplicationDbContext context,
            IConfiguration config,
            ILogger<EmailNotificationService> logger)
        {
            _context = context;
            _config = config;
            _logger = logger;
        }

        public async Task SendBookingAlertToAdminAsync(int bookingId)
        {
            // Aapka existing email alert code yahan rahega
        }

        public async Task SendPeriodicSummaryReportAsync()
        {
            var reservedCount = await _context.Bookings
                .AsNoTracking()
                .CountAsync(b => b.Status == "Confirmed");

            var checkedOutCount = await _context.Bookings
                .AsNoTracking()
                .CountAsync(b => b.Status == "Completed");

            var subject = "10-Minute Activity Summary: Villa Occupancy Report";
            var body = $@"
                <div style='font-family: Arial, sans-serif; padding: 18px; border: 1px solid #e2e8f0; border-radius: 8px;'>
                    <h3 style='color: #2F3E2E;'>MagicVilla Status Report</h3>
                    <p>Here is the automated 10-minute snapshot of the platform:</p>
                    <table style='width: 100%; border-collapse: collapse; margin-top: 10px;'>
                        <tr style='background: #f8fafc; text-align: left;'>
                            <th style='padding: 10px; border-bottom: 2px solid #cbd5e1;'>Metric</th>
                            <th style='padding: 10px; border-bottom: 2px solid #cbd5e1;'>Count</th>
                        </tr>
                        <tr>
                            <td style='padding: 10px; border-bottom: 1px solid #e2e8f0;'>Currently Reserved Villas</td>
                            <td style='padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: green;'>{reservedCount}</td>
                        </tr>
                        <tr>
                            <td style='padding: 10px; border-bottom: 1px solid #e2e8f0;'>Total Guests Checked Out</td>
                            <td style='padding: 10px; border-bottom: 1px solid #e2e8f0; font-weight: bold; color: #2563eb;'>{checkedOutCount}</td>
                        </tr>
                    </table>
                    <p style='font-size: 11px; color: #94a3b8; margin-top: 15px;'>Generated by Hangfire Recurring Automation.</p>
                </div>";

            var host = _config["EmailSettings:SmtpServer"];
            var port = int.Parse(_config["EmailSettings:Port"] ?? "2525");
            var username = _config["EmailSettings:Username"];
            var password = _config["EmailSettings:Password"];
            var sender = _config["EmailSettings:SenderEmail"] ?? "noreply@magicvilla.com";
            var admin = _config["EmailSettings:AdminEmail"] ?? "admin@magicvilla.com";

            using var client = new SmtpClient(host, port)
            {
                Credentials = new NetworkCredential(username, password),
                EnableSsl = true
            };

            var mail = new MailMessage(sender, admin, subject, body)
            {
                IsBodyHtml = true
            };

            await client.SendMailAsync(mail);
            _logger.LogInformation("Periodic summary email sent. Reserved: {R}, Checked Out: {C}", reservedCount, checkedOutCount);
        }
    }
}